pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
        - author=dependabot[bot]
        - author=github-actions[bot]
      - label=dependencies

      - check-success=Lint
    actions:
      merge:
        method: squash
